language: java
script: ./travis.sh

env:
  - TARGET=CI

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "target/files-archiver-.*-bin.zip"
  skip_cleanup: true
  on:
    tags: true
