language: java
dist: bionic
jdk:
- openjdk11
- openjdk8
cache:
  directories:
  - $HOME/.m2
git:
  depth: false
addons:
  sonarcloud:
    organization: axel3rd-github
before_script:
- echo Current build is on Java $JAVA_HOME
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package org.jacoco:jacoco-maven-plugin:report
- if [ "$JAVA_HOME" = "/usr/local/lib/jvm/openjdk11" ]; then mvn sonar:sonar; fi
