language: java
jdk:
 - oraclejdk7
 - oraclejdk8

# Run all integration tests and SonarQube GitHub integration only if PullRequest (and java 8 runner)
script:
 - mvn --batch-mode --errors --show-version clean verify
 - if [[ $(echo $JAVA_HOME | grep 8) && -n TRAVIS_PULL_REQUEST && $TRAVIS_PULL_REQUEST != "false" && -n $SONAR_TOKEN && -n $GITHUB_TOKEN ]]; then mvn --batch-mode --errors --show-version sonar:sonar -Dsonar.analysis.mode=preview -Dsonar.host.url=https://sonarqube.com -Dsonar.login=$SONAR_TOKEN -Dsonar.github.oauth=$GITHUB_TOKEN -Dsonar.github.pullRequest=$TRAVIS_PULL_REQUEST -Dsonar.github.repository=$TRAVIS_REPO_SLUG; fi
         
deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "target/files-archiver-.*-bin.zip"
  skip_cleanup: true
  on:
    tags: true
    
notifications:
  email: false
