language: java
jdk:
  - oraclejdk8

script:
 - mvn --batch-mode --errors --show-version clean verify
 - mvn --batch-mode --errors --show-version sonar:sonar \
    -Dsonar.analysis.mode=issues \
    -Dsonar.github.pullRequest=$TRAVIS_PULL_REQUEST \
    -Dsonar.github.repository=$TRAVIS_REPO_SLUG \
    -Dsonar.host.url=$SONAR_HOST_URL \
    -Dsonar.login=$SONAR_TOKEN \
    -Dsonar.github.oauth=$GITHUB_TOKEN
         
deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "target/files-archiver-.*-bin.zip"
  skip_cleanup: true
  on:
    tags: true
    
notifications:
  email: false
