language: java
dist: xenial
jdk:
- openjdk8
- oraclejdk11
cache:
  directories:
  - $HOME/.m2
git:
  depth: false
addons:
  sonarcloud:
    organization: axel3rd-github
before_script:
- echo Current build is on Java $JAVA_HOME
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package
- if [ "$JAVA_HOME" = "/usr/lib/jvm/java-1.8.0-openjdk-amd64" ]; then mvn sonar:sonar; fi
